title: Abhinav Vaishya
theme: jekyll-theme-primer
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# markdown processing
markdown: kramdown
kramdown:
  math_engine: mathjax
  # parse markdown inside HTML tags
  parse_block_html: true

# rss feed
author: "Abhinav Vaishya"
repository: abhinav-vaishya/abhinav-vaishya.github.io

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      excerpt_separator: "<!--more-->"

sass:
  load_paths:
    - _sass
    - assets/css
exclude:
  - .vs
  - vendor
  - scripts
  - README.md
